// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktrexsjqgtmxvhtvfocp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0cmV4c2pxZ3RteHZodHZmb2NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NTQxNDUsImV4cCI6MjA2NjEzMDE0NX0.7HGvPfny4TaAEqtNkitq3ZC8X78QDhX0hSYoLlKrD0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);